---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

<!-- badges: start -->
<!-- badges: end -->

# Robust Tools for Psychological Science

The research toolkit in psychological science has changed a lot in the last decade. Across many areas there is a heightened emphasis on transparency, open access, and a preference for the use of freely available tools. These skills are rarely taught during undergraduate psychology classes, and because research methods classes tend to be statistics heavy, they're rarely a part of research methodology classes either. This elective provides a hands on tutorial in how to use these tools: it covers an introduction to R programming, modern data visualisation and data wrangling, how to structure your projects, proper version control with git and GitHub, how to use OSF and PsyArXiv, and even how to write APA manuscripts from within R and set up a professional website to promote your work! The course is designed for novices, and no preexisting familiarity with these tools and no programming background is assumed. See https://github.com/djnavarro/robust-tools for details. 

**Notes on assessment:**

I'm on my way back from a conference and so won't be able to post a comprehensive description of the assessment until I get back, but a couple of people have asked so here's the gist...

The assessment will have two components: one part will be made up of a series of (very brief) quizzes on each section of the course (shouldn't be more than 10 minutes of work each week), and the other part will be a project of *your* choosing that uses the skills you've learned during the class (which can be written work, programming, whatever... each student will be able to discuss their projects with me). The final week of the class will consist of each student giving a brief presentation (~10-15 minutes) on what their project was about, and that presentation would count as part of the project for assessment purposes. 

## Week 1: Introduction to R & RStudio

- First commands
- Scripts
- Installing & loading packages
- Flow control with TurtleGraphics
- "Googling the error message" / StackOverflow / #rstats twitter


## Week 2: Introduction to data visualisation with ggplot

- Preliminary: Reading/writing from CSV
- The grammar of graphics
- Exploring the world of geoms
- Fun with facets
- Saving your plots
- Make it pretty...

## Week 3: Structuring a project

- Project directory templates
- Readme files
- RStudio projects
- Organising a collaboration

## Week 4: Behavioural experiments with jaysire

- Prelim: Introducing the pipe
- Structure of a broswer based experiment
- Using jaysire to write to jsPsych

## Week 5: Data wrangling with dplyr

[dplyr stuff here]

## Week 6: OSF, PsyArXiv

- OSF as archival storage 
- Creating an OSF account
- The OSF registrations system
- Understanding DOIs
- Sharing via PsyArXiv

## Week 7: Introduction to git & GitHub

- What is git? What is GitHub?
- Installing git, signup for GitHub
- Creating the repository on GitHub
- Cloning to local machine
- The edit/stage/commit/push cycle
- Issues threads & pull requests on GitHub
- The "burn it down" approach

## Week 8: Literate programming with R markdown

- Plain markdown
- R markdown
- A dash of LaTeX
- The YAML header
- Teaser: APA manuscripts with papaja
- Teaser: Professional websites with blogdown


## Week 9: Student presentations


