---
title: "00 :: Welcome to the class!"
author: Danielle Navarro
date: '2020-05-25'
slug: welcome-to-robust-tools
type: post
summary: "Before we get started, it helps to have an overview of the class. First, what is the class for?  Second, what do we hope to learn and why is this important for people who work in the social and behavioural sciences? Third, if we do want to do this class, what do we need to do to get started?"
---

<i class="fa fa-link"></i> Materials:

- [slides](welcome)
- [videos](https://youtu.be/t6IIJEoqPyk)

<br>

## What is this class for?

The research toolkit in the social and behavioural sciences has changed considerably over the last decade. Motivated in part by the need to make scientific work available to the general public and by widespread concerns about the reproducibility of scientific material, there has been a renewed emphasis on transparency, open access, and free open source tools.  

Perhaps surprisingly, learning how to use these tools rarely forms part of an undergraduate research methods course. In psychology, for example, research methods classes tend to focus heavily on inferential statistics, and other aspects to the research toolkit tend to be sidelined: my own [Learning Statistics with R](https://learningstatisticswithr.com) class is a good example of this oversight! 

The goal of this class is to fill in some of the gaps. It provides an introduction to R programming, modern data visualisation and data wrangling. It talks about how to structure projects, how to use version control, and how to write professional documents in R. The course is designed for novices --- no preexisting familiarity with these tools is expected, and no programming background is assumed.

## Our learning goals

TBA

## Running R in the cloud

Once upon a time, when I taught classes on R programming I would have to spend the first hour getting students set up with a working local copy of R on their own machines. This isn't actually too difficult to do *once you already know what you're doing*, but it can be finicky and it's an unbearably dull place to start. To make our lives easier, this course relies on [RStudio Cloud](https://rstudio.cloud): you can have a fully functional version of R running through the browser with minimal effort. Each section will link to a specific "RStudio Cloud Project"


## Let's get started!

For this section, as well as later ones, I have made the [slides](welcome) publicly available, and have posted video of me presenting the slides to [youtube](https://youtu.be/t6IIJEoqPyk). 


